import environ

env = environ.Env()
environ.Env.read_env()

ELASTIC_SERVER_URL = env('ELASTIC_SERVER_URL')
ELASTIC_SERVER_USER = env('ELASTIC_SERVER_USER')
ELASTIC_SERVER_PASSWORD = env('ELASTIC_SERVER_PASSWORD')
PAGE_SIZE = 100
MAX_PAGE_SIZE = 10000
FILE_SYSTEM_URL = env('FILE_SYSTEM_URL')

ELASTIC_SERVER_LOGS_URL = env('ELASTIC_SERVER_LOGS_URL')
ELASTIC_SERVER_LOGS_USER = env('ELASTIC_SERVER_LOGS_USER')
ELASTIC_SERVER_LOGS_PASSWORD = env('ELASTIC_SERVER_LOGS_PASSWORD')
